config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :home, only: [:index]
  resources :jobs do
    resources :entries, only: [:create]
  end
  devise_for :users
  resources :users, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :job
  
  validates :user_id, uniqueness: { scope: :job_id }

end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :entries, -> { order(created_at: :desc) }, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :status, presence: true
  validates :annualSalary, presence: true
  validates :benefitProgram, presence: true
  validates :holiday, presence: true
  validates :corporateName, presence: true

  enum status: {
    正社員:0,契約社員:1,業務委託:2,インターン:3,パート・アルバイト:4
  }
  
  enum workplace: {
    リモート勤務可:0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :jobs, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  validates :familyName, presence: true
  validates :familyNameDetail, presence: true
  validates :lastName, presence: true
  validates :lastNameDetail, presence: true
  validates :gender, presence: true
  validates :birthdate, presence: true
  validates :location, presence: true
  
  enum gender: {
    男性:0,女性:1
  }
  
  enum location: {
    北海道:0,青森県:1,岩手県:2,宮城県:3,秋田県:4,山形県:5,福島県:6,
    茨城県:7,栃木県:8,群馬県:9,埼玉県:10,千葉県:11,東京都:12,神奈川県:13,
    新潟県:14,富山県:15,石川県:16,福井県:17,山梨県:18,長野県:19,
    岐阜県:20,静岡県:21,愛知県:22,三重県:23,
    滋賀県:24,京都府:25,大阪府:26,兵庫県:27,奈良県:28,和歌山県:29,
    鳥取県:30,島根県:31,岡山県:32,広島県:33,山口県:34,
    徳島県:35,香川県:36,愛媛県:37,高知県:38,
    福岡県:39,佐賀県:40,長崎県:41,熊本県:42,大分県:43,宮崎県:44,鹿児島県:45,
    沖縄県:46,リモート:47
  }, _prefix: true
  
  enum workplace: {
    北海道:0,青森県:1,岩手県:2,宮城県:3,秋田県:4,山形県:5,福島県:6,
    茨城県:7,栃木県:8,群馬県:9,埼玉県:10,千葉県:11,東京都:12,神奈川県:13,
    新潟県:14,富山県:15,石川県:16,福井県:17,山梨県:18,長野県:19,
    岐阜県:20,静岡県:21,愛知県:22,三重県:23,
    滋賀県:24,京都府:25,大阪府:26,兵庫県:27,奈良県:28,和歌山県:29,
    鳥取県:30,島根県:31,岡山県:32,広島県:33,山口県:34,
    徳島県:35,香川県:36,愛媛県:37,高知県:38,
    福岡県:39,佐賀県:40,長崎県:41,熊本県:42,大分県:43,宮崎県:44,鹿児島県:45,
    沖縄県:46,リモート:47
  }, _prefix: true       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:familyName, :lastName, :familyNameDetail, :lastNameDetail, :gender, :birthdate, :location])
    devise_parameter_sanitizer.permit(:account_update, keys: [:familyName, :lastName, :familyNameDetail, :lastNameDetail, :gender, :birthdate, :location, :education, :career, :reason, :strongPoint, :weakPoint, :goal, :learningResource, :informationResource, :programmingLanguage, :portfolio, :futureProduct, :introduction, :workplace, :annualSalary, :startingDate])
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    job = Job.find(params[:job_id])
    @entry = current_user.entries.build do |e|
      e.job = job
    end

    if @entry.save
      redirect_to root_path, notice: "応募が完了しました"
    end  
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
before_action :authenticate_user!, only: [:show, :new, :create, :efit, :update, :destroy]
  
  def index
    @jobs = Job.all.order(id: "DESC")
  end

  def show
    @job = Job.find_by(id: params[:id])
  end

  def new
    @job = Job.new
  end
  
  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
      flash[:notice] = "投稿しました"
    else
      flash[:alert] = "Save error"
      render :new
    end  
  end

  def edit
    @job = Job.find_by(id: params[:id])
  end
  
  def update
    @job = Job.find_by(id: params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
      flash[:notice] = "投稿しました"
    else
      flash[:alert] = "Save error"
      render :edit
    end  
  end
  
  def destroy
    @job = Job.find_by(id: params[:id])
    if @job.user == current_user
      flash[:notice] = "削除しました" if @job.destroy
    else
      flash[:alert] = "Save error"
    end
    redirect_to jobs_path
  end
  
  private
    def job_params
      params.require(:job).permit(:title, :description, :status, :annualSalary, :programmingLanguage, :skillset, :benefitProgram, :holiday, :desiredCharacteristics, :selectionProcess, :startingDate, :workplace, :access, :corporateName, :corporateUrl, :industry, :address, :introduction).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @entries = Entry.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end
  
  private
    def user_params
      params.require(:job).permit(:email, :password, :familyName, :lastName, :familyNameDetail, :lastNameDetail, :gender, :birthdate, :location, :education, :career, :reason, :strongPoint, :weakPoint, :goal, :learningResource, :informationResource, :programmingLanguage, :portfolio, :futureProduct, :introduction, :workplace, :annualSalary, :startingDate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% unless user_signed_in?%>
<h2 class="mb-5">働かざるを得ない</h2>
  <p>社会は厳しいです。</p>
  <p>自己肯定感は低下し、劣等感が増す一方になります。</p>
  <p>技術力に裏打ちされた確固たる自信をもって働きましょう。</p>
<% end %>  

<h3>お問合せについて</h3>
<p>お問合せは<strong>jeopardy1216@gmail.com</strong>までお願いいたします。</br>3日以内に返信いたします。営業目的でのお問合せはお断りしております。</p>
<h3>寄付について</h3>
<p>お金に困っています。助けてください。以下振込先情報になります。</br>差し支えなければ、<strong>jeopardy1216@gmail.com</strong>宛にお名前とご住所をお送りください。</br>金額の多寡にかかわらずお礼のお手紙を送らせていただきます。</p>
<dl>
  <dt>銀行</dt>
  <dd>楽天銀行</dd>
  <dt>口座番号</dt>
  <dd>3117893</dd>
  <dt>支店名(番号)</dt>
  <dd>アロハ支店(221)</dd>
  <dt>口座名義</dt>
  <dd>二木孝幸(フタツギタカユキ)</dd>
</dl>

<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <div class="ui form">
        <div class="field">
          <label>Username</label>
          <div class="ui left icon input">
            <input type="text" placeholder="Username">
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <label>Password</label>
          <div class="ui left icon input">
            <input type="password">
            <i class="lock icon"></i>
          </div>
        </div>
        <div class="ui blue submit button">Login</div>
      </div>
    </div>
    <div class="middle aligned column">
      <div class="ui big button">
        <i class="signup icon"></i>
        Sign Up
      </div>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>

app/views/jobs/edit.html.erb
<h2 class="mb-5">求人情報編集</h2>
<%= form_with model:@job do |f| %>
  
  <div>
    <h3 class="mb-4">求人情報</h3>
    
    <div class="field mb-2"><%= f.label :仕事タイトル %>(必須)：<%= f.text_field :title %></div>
    <div class="field mb-2"><%= f.label :雇用形態 %>(必須)：<%= f.select :status, Job.statuses.keys, {} %></div>
    <div class="field mb-2"><%= f.label :想定年収 %>(必須)：約<%= f.text_field :annualSalary %>万円</div>
    <div class="field mb-2"><%= f.label :使用言語・フレームワーク %>：<%= f.text_field :programmingLanguage %></div>
    <div class="field mb-2"><%= f.label :歓迎スキル %>：<%= f.text_field :skillset %></div>
    <div class="field mb-2"><%= f.label :待遇・福利厚生 %>(必須)：<%= f.text_field :benefitProgram %></div>
    <div class="field mb-2"><%= f.label :休日・休暇 %>(必須)：<%= f.text_field :holiday %></div>
    <div class="field mb-2"><%= f.label :求める人物像 %>：<%= f.text_field :desiredCharacteristics %></div>
    <div class="field mb-2"><%= f.label :選考プロセス %>：<%= f.text_field :selectionProcess %></div>
    <div class="field mb-2"><%= f.label :勤務開始予定日 %>：<%= f.date_select(:startingDate, start_year: Date.today.year, end_year: Date.today.year+2) %></div>
    <div class="field mb-2"><%= f.label :勤務地 %>：<%= f.select :workplace, Job.workplaces.keys, {} %></div>
    <div class="field mb-2"><%= f.label :アクセス %>：<%= f.text_field :access %></div>
    <div class="field mb-2"><%= f.label :詳細情報 %>(必須)：<%= f.text_area :description %></div>
  </div>
  
  <div>
    <h3 class="mb-4">会社情報</h3>
    
    <div class="field mb-2"><%= f.label :会社名 %>(必須)：<%= f.text_field :corporateName %></div>
    <div class="field mb-2"><%= f.label :会社ホームページ %>：<%= f.text_field :corporateUrl %></div>
    <div class="field mb-2"><%= f.label :業種・事業内容 %>：<%= f.text_field :industry %></div>
    <div class="field mb-2"><%= f.label :本社所在地 %>：<%= f.text_field :address %></div>
    <div class="field mb-2"><%= f.label :会社紹介 %>：<%= f.text_area :introduction %></div>
  </div>
  
  <%= f.submit "変更を保存", class: "btn btn-primary btn-lg" %>
  
<% end %>

app/views/jobs/index.html.erb
<div class="d-flex mb-5">
  <h2>求人一覧</h2>
  <div class="ml-auto">
    <%= link_to "新規投稿", new_job_path,class: "btn btn-primary btn-lg" %>
  </div>
</div>

<% @jobs.each do |job| %>
  <div class="card mb-2">
    <div class="card-body">
      <div class="d-flex">
        <p>会社名：<%= job.corporateName %></p>
        <p class="ml-auto"><%= job.created_at %></p>
      </div>
      <p>仕事タイトル：<%= link_to link_to job.title, job_path(job) %></p>
      <p>仕事詳細：<%= truncate job.description, length: 50, omission: '...' %></p>
      <p>雇用形態：<%= job.status %>　 　想定年収：約<%= job.annualSalary %>万円</p>
    </div>
  </div>
<% end %>

app/views/jobs/new.html.erb
<h2 class="mb-5">求人新規投稿</h2>
<%= form_with model:@job do |f| %>
  
  <div>
    <h3 class="mb-4">求人情報</h3>
    
    <div class="field mb-2"><%= f.label :仕事タイトル %>(必須)：<%= f.text_field :title %></div>
    <div class="field mb-2"><%= f.label :雇用形態 %>(必須)：<%= f.select :status, Job.statuses.keys, {} %></div>
    <div class="field mb-2"><%= f.label :想定年収 %>(必須)：約<%= f.text_field :annualSalary %>万円</div>
    <div class="field mb-2"><%= f.label :使用言語・フレームワーク %>：<%= f.text_field :programmingLanguage %></div>
    <div class="field mb-2"><%= f.label :歓迎スキル %>：<%= f.text_field :skillset %></div>
    <div class="field mb-2"><%= f.label :待遇・福利厚生 %>(必須)：<%= f.text_field :benefitProgram %></div>
    <div class="field mb-2"><%= f.label :休日・休暇 %>(必須)：<%= f.text_field :holiday %></div>
    <div class="field mb-2"><%= f.label :求める人物像 %>：<%= f.text_field :desiredCharacteristics %></div>
    <div class="field mb-2"><%= f.label :選考プロセス %>：<%= f.text_field :selectionProcess %></div>
    <div class="field mb-2"><%= f.label :勤務開始予定日 %>：<%= f.date_select(:startingDate, start_year: Date.today.year, end_year: Date.today.year+2) %></div>
    <div class="field mb-2"><%= f.label :勤務地 %>：<%= f.select :workplace, Job.workplaces.keys, {} %></div>
    <div class="field mb-2"><%= f.label :アクセス %>：<%= f.text_field :access %></div>
    <div class="field mb-2"><%= f.label :詳細情報 %>(必須)：<%= f.text_area :description %></div>
  </div>
  
  <div>
    <h3 class="mb-4">会社情報</h3>
    
    <div class="field mb-2"><%= f.label :会社名 %>(必須)：<%= f.text_field :corporateName %></div>
    <div class="field mb-2"><%= f.label :会社ホームページ %>：<%= f.text_field :corporateUrl %></div>
    <div class="field mb-2"><%= f.label :業種・事業内容 %>：<%= f.text_field :industry %></div>
    <div class="field mb-2"><%= f.label :本社所在地 %>：<%= f.text_field :address %></div>
    <div class="field mb-2"><%= f.label :会社紹介 %>：<%= f.text_area :introduction %></div>
  </div>
  
  <%= f.submit "投稿", class: "btn btn-primary btn-lg" %>
  
<% end %>

app/views/jobs/show.html.erb
  <div class="d-flex mb-5">
    <h2>求人詳細</h2>
    <div class="ml-auto">
      <% if @job.user_id == current_user.id %>
        <%= link_to "削除", job_path(@job), data: { confirm: "本当に削除してよろしいですか?" }, method: :delete, class: "btn btn-danger btn-lg" %>
        <%= link_to "編集", edit_job_path(@job), class: "btn btn-primary btn-lg" %>
      <% else %>
        <%= link_to "応募", job_entries_path(@job), data: { confirm: "ユーザーデータが企業に送られます。応募してよろしいですか?" }, method: :post, class:"btn btn-primary btn-lg" %>
      <% end %>
    </div>
  </div>
  
    <div>
      <h3 class="mb-4">求人情報</h3>
      
      <p class="mb-2">仕事タイトル：<%= @job.title %></p>
      <p class="mb-2">雇用形態：<%= @job.status %></p>
      <p class="mb-2">想定年収：<%= @job.annualSalary %></p>
      <p class="mb-2">使用言語・フレームワーク：<%= @job.programmingLanguage %></p>
      <p class="mb-2">歓迎スキル：<%= @job.skillset %></p>
      <p class="mb-2">待遇・福利厚生：<%= @job.benefitProgram %></p>
      <p class="mb-2">休日・休暇：<%= @job.holiday %></p>
      <p class="mb-2">求める人物像：<%= @job.desiredCharacteristics %></p> 
      <p class="mb-2">選考プロセス：<%= @job.selectionProcess %></p>
      <p class="mb-2">勤務開始予定日：<%= @job.startingDate %></p>
      <p class="mb-2">勤務地：<%= @job.workplace %></p>
      <p class="mb-2">アクセス：<%= @job.access %></p>
      <p class="mb-2">詳細情報：<%= @job.description %></p> 
      <p class="mb-2">選考プロセス：<%= @job.selectionProcess %></p>
    </div>
    
    <div>
      <h3 class="mb-4">会社情報</h3>
      
      <p class="mb-2">会社名：<%= @job.corporateName %></p>
      <p class="mb-2">会社ホームページ：<%= @job.corporateUrl %></p>
      <p class="mb-2">業種・事業内容：<%= @job.industry %></p>
      <p class="mb-2">本社所在地：<%= @job.address %></p> 
      <p class="mb-2">会社紹介：<%= @job.introduction %></p>
    </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recruit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--<p class="notice"><%= notice %></p>-->
    <!--<p class="alert"><%= alert %></p>-->
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
      <div class="container">
        <% if user_signed_in? %>
          <h1><%= current_user.familyName + current_user.lastName %>様</h1>
        <% else %>
          <h1>家賃滞納侍</h1>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <%= link_to "求人一覧", jobs_path, class: "nav-item nav-link" %>
            <%= link_to "応募者一覧", users_path, class: "nav-item nav-link" %>
            <%= link_to "プロフィール編集", edit_user_registration_path, class: "nav-item nav-link" %>
            <%= link_to "お問合せ", home_index_path, class: "nav-item nav-link" %>
            <% if user_signed_in? %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
            <% else %>
              <%= link_to "新規登録・ログイン", user_session_path, class: "nav-item nav-link" %>
            <% end %>
          </div>
        </div>  
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    <p class="text-center">&copy;家賃滞納侍</p>
  </body>
</html>

app/views/users/index.html.erb
<h2 class="mb-5">応募一覧</h2>
<% @entries.each do |entry| %>
  <% if entry.job.user_id == current_user.id %>
    <div class="card mb-2">
      <div class="card-body">
        <div class="d-flex">
          <p><%= entry.job.title %></p>
          <p class="ml-auto"><%= entry.created_at %></p>
        </div>
        <p>氏名：<%= link_to entry.user.familyName + entry.user.lastName, user_path(entry.user) %></p>
        <p>性別：<%= entry.user.gender %>　　生年月日：<%= entry.user.birthdate %>　　居住地：<%= entry.user.location %></p>
      </div>
    </div>
  <% end %>
 
<% end %>

app/views/users/show.html.erb
<h2 class="mb-5"><%= @user.familyName %> <%= @user.lastName %>様詳細プロフィール</h2>
<p>氏名：<%= @user.familyName %> <%= @user.lastName %> (<%= @user.familyNameDetail %> <%= @user.lastNameDetail %>)</p>
<p>性別：<%= @user.gender %>　　生年月日：<%= @user.birthdate %>　　居住地：<%= @user.location %></p>
<p>メールアドレス：<%= @user.email %></p>
<p>学歴：<%= @user.education %></p>
<p>職歴：<%= @user.career %></p>
<p>エンジニアになる理由：<%= @user.reason %></p>
<p>長所：<%= @user.strongPoint %>　　短所：<%= @user.weakPoint %></p>
<p>エンジニアとしての目標：<%= @user.goal %></p>
<p>学習に使っているサイト・書籍：<%= @user.learningResource %></p>
<p>情報収集に使っているサイト・書籍：<%= @user.informationResource %></p>
<p>学習した言語・フレームワーク：<%= @user.programmingLanguage %></p>
<p>ポートフォリオ：<%= @user.portfolio %></p>
<p>作ってみたいプロダクト：<%= @user.futureProduct %></p>
<p>自己紹介：<%= @user.introduction %></p>
<p>希望勤務地：<%= @user.workplace %></p>
<p>希望年収：約<%= @user.annualSalary %>万円</p>
<p>勤務開始可能日：<%= @user.startingDate %></p>